name: Tag on PR Merge (frontend/backend)

on:
  push:
  workflow_dispatch:

# permissions:
#   contents: write
# pull-requests: read

jobs:
  tag:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags --force

      - name: Read PR labels
        id: labels
        run: |
          labels='${{ toJson(github.event.pull_request.labels) }}'
          echo "labels: $labels"
